### ISSUE TITLE
Galat saat meneruskan pesan

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#145]
```
2main.js:30089 TypeError: window.html2text is not a function
   at o.composeMessage (https://$DOMAIN/js/main.js:53:23842)
   at fn (eval at <anonymous> (https://$DOMAIN/js/main.js:15:13097), <anonymous>:4:454)
   at o (https://$DOMAIN/js/main.js:16:183)
   at h.$eval (https://$DOMAIN/js/main.js:11:32006)
   at h.$apply (https://$DOMAIN/js/main.js:13:223)
   at HTMLButtonElement.<anonymous> (https://$DOMAIN/js/main.js:16:235)
   at HTMLButtonElement.We.n (https://$DOMAIN/js/main.js:10:10720)
```
- Isi surat yang mau diteruskan tidak ada
- Ada lebih dari 4 popup: sambungan bermasalah
- Jendela komposer yang kosong tadi ditutup dengan pencet X

```
DELETE https://$DOMAIN/api/1.0/message?seqs=44&messageId=1456964503688-dbd17481-bf3dcec8-16af91c0%40pnsmail.go.id&boxName=Drafts 500 (Internal Server Error)
```
- Muncul popup Draf berhasil disimpan
- Muncul sambungan bermasalah berkali-kali

**Comment by emhaye** [comment]
1. buka surel
2. forward
3. tutup pakai x
4. buka surel lain
5. forward
6. tutup pakai x
7. galat
