### ISSUE TITLE
Surelia crashed randomly when an error throwed from imap library

### ISSUE THREAD

**Issue by herpiko** [KodeKreatif/surelia-web-client#168]

**Comment by herpiko** [comment]
```
➜  surelia-web-client git:(shrinkwrap) ✗ npm run single

> surelia-web-client@0.0.1 single /home/herpiko/src/mail/surelia-web-client
> npm run build && NODE_TLS_REJECT_UNAUTHORIZED=0 node index single


> surelia-web-client@0.0.1 build /home/herpiko/src/mail/surelia-web-client
> rm -rf public && ./node_modules/.bin/gulp prod

[02:15:24] Using gulpfile ~/src/mail/surelia-web-client/gulpfile.js
[02:15:24] Starting 'clean'...
[02:15:24] Finished 'clean' after 4.9 ms
[02:15:24] Starting 'prod'...
[02:15:24] Starting 'db'...
[02:15:24] Finished 'db' after 9.62 ms
[02:15:24] Starting 'surelia'...
[02:15:25] Finished 'surelia' after 1.72 ms
[02:15:25] Starting 'styles'...
[02:15:25] Starting 'images'...
[02:15:25] Starting 'fonts'...
[02:15:25] Starting 'views'...
[02:15:25] Starting 'browserify'...
[02:15:25] Rebundle...
[02:15:25] gulp-imagemin: Minified 0 images
[02:15:25] Finished 'images' after 64 ms
[02:15:25] Finished 'views' after 544 ms
[02:15:26] Finished 'styles' after 1.22 s
[02:15:26] Finished 'fonts' after 1.22 s
[02:15:56] Finished 'browserify' after 32 s
[02:15:56] Starting 'gzip'...
[02:15:57] Finished 'gzip' after 552 ms
[02:15:57] Finished 'prod' after 32 s
{}
{ mongodbUrl: 'mongodb://localhost/test' }
{}
{}
{}
{ gearmanServer: false }
info: GearmaNode 0.9.2, running on Node.js v4.2.1 [linux x64], with pid 23397
server is running at 3000
a client connected
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
update seq for herpiko.email.testing@gmail.com room
a client connected
a client join herpiko.email.testing@gmail.com room
name INBOX
limit 10
page 1
fetchLimit 24
start 15
seqArray 15,16,17,18,19,20,21,22,23,24
options {"search":""}
search criteria OR,SUBJECT,,FROM,
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: FETCH not allowed now.
    at Connection._resTagged (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Connection.js:1485:11)
    at Parser.<anonymous> (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Connection.js:193:10)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._resTagged (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/herpiko/src/mail/surelia-web-client/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
    at Socket.<anonymous> (_stream_wrap.js:48:20)

npm ERR! Linux 4.6.0-1-63
npm ERR! argv "/home/herpiko/.nvm/versions/node/v4.2.1/bin/node" "/home/herpiko/.nvm/versions/node/v4.2.1/bin/npm" "run" "single"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! surelia-web-client@0.0.1 single: `npm run build && NODE_TLS_REJECT_UNAUTHORIZED=2 node index single`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the surelia-web-client@0.0.1 single script 'npm run build && NODE_TLS_REJECT_UNAUTHORIZED=0 node index single'.
npm ERR! This is most likely a problem with the surelia-web-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && NODE_TLS_REJECT_UNAUTHORIZED=0 node index single
npm ERR! You can get their info via:
npm ERR!     npm owner ls surelia-web-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/herpiko/src/mail/surelia-web-client/npm-debug.log

```

**Comment by herpiko** [comment]
Also the error from #132 could do this.
